explain analyze SELECT * FROM store WHERE store.market_id <= 8 AND store.market_id >= 4;
explain analyze SELECT * FROM store WHERE store.number_employees <= 297 AND store.number_employees >= 294 AND store.devision_id <= 1 AND store.devision_id >= 1;
explain analyze SELECT * FROM store WHERE store.company_id <= 255 AND store.company_id >= 175;
explain analyze SELECT * FROM customer WHERE customer.birth_year <= 1984.0 AND customer.birth_year >= 1933.0;
explain analyze SELECT * FROM customer WHERE customer.birth_year <= 1983.0 AND customer.birth_year >= 1956.0;
explain analyze SELECT * FROM promotion WHERE promotion.cost <= 1000.0 AND promotion.cost >= 1000.0;
explain analyze SELECT * FROM promotion WHERE promotion.response_target <= 1.0 AND promotion.response_target >= 1.0;
explain analyze SELECT * FROM item;
explain analyze SELECT * FROM customer;
explain analyze SELECT * FROM customer;
explain analyze SELECT * FROM store_sales WHERE store_sales.sales_price <= 28.97 AND store_sales.sales_price >= 24.99 AND store_sales.ext_tax <= 14.05 AND store_sales.ext_tax >= 7.51 AND store_sales.ext_coupon_amt <= 0.0 AND store_sales.ext_coupon_amt >= -1.0 AND store_sales.net_paid <= 8272.0 AND store_sales.net_paid >= 1084.89 AND store_sales.net_paid_inc_tax <= 2455.76 AND store_sales.net_paid_inc_tax >= -1.0 AND store_sales.net_profit <= 247.51 AND store_sales.net_profit >= -2888.6;
explain analyze SELECT * FROM promotion WHERE promotion.response_target <= 1.0 AND promotion.response_target >= 1.0;
explain analyze SELECT * FROM store_sales WHERE store_sales.quantity <= 52.0 AND store_sales.quantity >= 5.0 AND store_sales.ext_wholesale_cost <= 3805.56 AND store_sales.ext_wholesale_cost >= 378.84 AND store_sales.net_paid <= 238.5 AND store_sales.net_paid >= 188.18;
explain analyze SELECT * FROM customer;
explain analyze SELECT * FROM store WHERE store.number_employees <= 294 AND store.number_employees >= 236 AND store.floor_space <= 7557959 AND store.floor_space >= 5285950;
explain analyze SELECT * FROM promotion WHERE promotion.cost <= 1000.0 AND promotion.cost >= 1000.0;
explain analyze SELECT * FROM item WHERE item.current_price <= 8.82 AND item.current_price >= 6.48;
explain analyze SELECT * FROM item WHERE item.manufact_id <= 570.0 AND item.manufact_id >= 87.0;
explain analyze SELECT * FROM customer WHERE customer.birth_day <= 26.0 AND customer.birth_day >= 10.0;
explain analyze SELECT * FROM store WHERE store.floor_space <= 5250760 AND store.floor_space >= 5219562;
explain analyze SELECT * FROM promotion;
explain analyze SELECT * FROM promotion;
explain analyze SELECT * FROM item WHERE item.current_price <= 52.25 AND item.current_price >= 8.09 AND item.manufact_id <= 518.0 AND item.manufact_id >= 146.0;
explain analyze SELECT * FROM customer;
explain analyze SELECT * FROM store_sales WHERE store_sales.sales_price <= 87.28 AND store_sales.sales_price >= 10.18 AND store_sales.ext_discount_amt <= 166.14 AND store_sales.ext_discount_amt >= 0.0 AND store_sales.ext_sales_price <= 239.68 AND store_sales.ext_sales_price >= 4.28 AND store_sales.ext_list_price <= 4342.64 AND store_sales.ext_list_price >= 1687.5 AND store_sales.ext_tax <= 63.14 AND store_sales.ext_tax >= 9.38;
explain analyze SELECT * FROM promotion;
explain analyze SELECT * FROM customer WHERE customer.birth_month <= 5.0 AND customer.birth_month >= 2.0;
explain analyze SELECT * FROM customer WHERE customer.birth_year <= 1966.0 AND customer.birth_year >= 1940.0;
explain analyze SELECT * FROM store;
explain analyze SELECT * FROM store WHERE store.devision_id <= 1 AND store.devision_id >= 1 AND store.company_id <= 337 AND store.company_id >= 27;
explain analyze SELECT * FROM customer WHERE customer.birth_day <= 18.0 AND customer.birth_day >= 14.0;
explain analyze SELECT * FROM customer WHERE customer.birth_month <= 6.0 AND customer.birth_month >= -1.0;
explain analyze SELECT * FROM store WHERE store.floor_space <= 6995995 AND store.floor_space >= 5219562;
explain analyze SELECT * FROM promotion WHERE promotion.cost <= 1000.0 AND promotion.cost >= 1000.0;
explain analyze SELECT * FROM store;
explain analyze SELECT * FROM promotion;
explain analyze SELECT * FROM promotion;
explain analyze SELECT * FROM store_sales WHERE store_sales.quantity <= 31.0 AND store_sales.quantity >= 13.0 AND store_sales.ext_wholesale_cost <= 3913.91 AND store_sales.ext_wholesale_cost >= 2181.27 AND store_sales.net_paid_inc_tax <= 2539.78 AND store_sales.net_paid_inc_tax >= 2508.48 AND store_sales.net_profit <= 58.29 AND store_sales.net_profit >= -1525.14;
explain analyze SELECT * FROM customer;
explain analyze SELECT * FROM item WHERE item.brand_id <= 8003002.0 AND item.brand_id >= 8002010.0;
explain analyze SELECT * FROM customer;
explain analyze SELECT * FROM store WHERE store.floor_space <= 9341467 AND store.floor_space >= 9026222 AND store.market_id <= 10 AND store.market_id >= 2;
explain analyze SELECT * FROM store;
explain analyze SELECT * FROM store WHERE store.company_id <= 255 AND store.company_id >= 175 AND store.tax_percentage <= 0.08 AND store.tax_percentage >= 0.03;
explain analyze SELECT * FROM store WHERE store.tax_percentage <= 0.11 AND store.tax_percentage >= 0.08;
explain analyze SELECT * FROM promotion;
explain analyze SELECT * FROM store;
explain analyze SELECT * FROM item WHERE item.current_price <= 17.32 AND item.current_price >= 3.04 AND item.manufact_id <= 277.0 AND item.manufact_id >= 159.0;
explain analyze SELECT * FROM item;
explain analyze SELECT * FROM store_sales WHERE store_sales.sales_price <= 88.58 AND store_sales.sales_price >= 51.52 AND store_sales.ext_sales_price <= 1800.96 AND store_sales.ext_sales_price >= 84.4 AND store_sales.ext_wholesale_cost <= 1785.0 AND store_sales.ext_wholesale_cost >= 928.34 AND store_sales.net_paid <= 949.62 AND store_sales.net_paid >= 38.82 AND store_sales.net_paid_inc_tax <= 159.24 AND store_sales.net_paid_inc_tax >= 101.75;
explain analyze SELECT * FROM store WHERE store.floor_space <= 9078805 AND store.floor_space >= 5219562 AND store.company_id <= 27 AND store.company_id >= 27;
explain analyze SELECT * FROM promotion WHERE promotion.cost <= 1000.0 AND promotion.cost >= 1000.0;
explain analyze SELECT * FROM promotion WHERE promotion.cost <= 1000.0 AND promotion.cost >= 1000.0;
explain analyze SELECT * FROM item;
explain analyze SELECT * FROM item WHERE item.category_id <= 4.0 AND item.category_id >= 3.0;
explain analyze SELECT * FROM store_sales WHERE store_sales.list_price <= 147.94 AND store_sales.list_price >= 119.26 AND store_sales.sales_price <= 11.84 AND store_sales.sales_price >= 5.11 AND store_sales.ext_tax <= 30.47 AND store_sales.ext_tax >= 0.0 AND store_sales.ext_coupon_amt <= 0.0 AND store_sales.ext_coupon_amt >= 0.0;
explain analyze SELECT * FROM store_sales WHERE store_sales.ext_sales_price <= 2597.49 AND store_sales.ext_sales_price >= 683.4 AND store_sales.ext_tax <= 42.12 AND store_sales.ext_tax >= 26.17 AND store_sales.net_paid_inc_tax <= 64.71 AND store_sales.net_paid_inc_tax >= -1.0;
explain analyze SELECT * FROM store WHERE store.company_id <= 811 AND store.company_id >= 226;
explain analyze SELECT * FROM item WHERE item.category_id <= 9.0 AND item.category_id >= 6.0;
explain analyze SELECT * FROM promotion;
explain analyze SELECT * FROM store WHERE store.number_employees <= 294 AND store.number_employees >= 236 AND store.floor_space <= 7557959 AND store.floor_space >= 5285950 AND store.company_id <= 255 AND store.company_id >= 220;
explain analyze SELECT * FROM store_sales;
explain analyze SELECT * FROM customer WHERE customer.birth_day <= 18.0 AND customer.birth_day >= 6.0;
explain analyze SELECT * FROM customer WHERE customer.birth_year <= 1946.0 AND customer.birth_year >= 1943.0;
explain analyze SELECT * FROM store_sales;
explain analyze SELECT * FROM item WHERE item.current_price <= 9.19 AND item.current_price >= 2.01 AND item.category_id <= 7.0 AND item.category_id >= 5.0;
explain analyze SELECT * FROM customer WHERE customer.birth_month <= 7.0 AND customer.birth_month >= 2.0;
explain analyze SELECT * FROM store_sales;
explain analyze SELECT * FROM store;
explain analyze SELECT * FROM promotion;
explain analyze SELECT * FROM store WHERE store.number_employees <= 294 AND store.number_employees >= 294 AND store.market_id <= 10 AND store.market_id >= 2;
explain analyze SELECT * FROM customer;
explain analyze SELECT * FROM item WHERE item.brand_id <= 7016003.0 AND item.brand_id >= 7005007.0;
explain analyze SELECT * FROM promotion;
explain analyze SELECT * FROM promotion WHERE promotion.response_target <= 1.0 AND promotion.response_target >= 1.0;
explain analyze SELECT * FROM promotion;
explain analyze SELECT * FROM item WHERE item.category_id <= 9.0 AND item.category_id >= 9.0 AND item.manufact_id <= 572.0 AND item.manufact_id >= 461.0;
explain analyze SELECT * FROM item WHERE item.manufact_id <= 119.0 AND item.manufact_id >= 29.0;
explain analyze SELECT * FROM item;
explain analyze SELECT * FROM customer WHERE customer.birth_month <= 11.0 AND customer.birth_month >= 5.0;
explain analyze SELECT * FROM promotion;
explain analyze SELECT * FROM item;
explain analyze SELECT * FROM store WHERE store.number_employees <= 294 AND store.number_employees >= 236;
explain analyze SELECT * FROM customer WHERE customer.birth_day <= 22.0 AND customer.birth_day >= 2.0;
explain analyze SELECT * FROM store WHERE store.floor_space <= 6995995 AND store.floor_space >= 5219562;
explain analyze SELECT * FROM store_sales WHERE store_sales.sales_price <= 81.72 AND store_sales.sales_price >= 3.72 AND store_sales.ext_wholesale_cost <= 5837.76 AND store_sales.ext_wholesale_cost >= 46.8 AND store_sales.ext_list_price <= 3226.08 AND store_sales.ext_list_price >= 2846.58;
explain analyze SELECT * FROM item;
explain analyze SELECT * FROM store_sales WHERE store_sales.sales_price <= 83.02 AND store_sales.sales_price >= 18.18 AND store_sales.ext_discount_amt <= 80.11 AND store_sales.ext_discount_amt >= 0.0 AND store_sales.ext_sales_price <= 2202.1 AND store_sales.ext_sales_price >= -1.0 AND store_sales.ext_wholesale_cost <= 2868.1 AND store_sales.ext_wholesale_cost >= 595.2 AND store_sales.net_paid_inc_tax <= 301.12 AND store_sales.net_paid_inc_tax >= 104.59;
explain analyze SELECT * FROM item WHERE item.class_id <= 3.0 AND item.class_id >= 2.0;
explain analyze SELECT * FROM promotion;
explain analyze SELECT * FROM promotion WHERE promotion.response_target <= 1.0 AND promotion.response_target >= 1.0;
explain analyze SELECT * FROM customer;
explain analyze SELECT * FROM item WHERE item.category_id <= 5.0 AND item.category_id >= 3.0;
explain analyze SELECT * FROM customer WHERE customer.birth_month <= 7.0 AND customer.birth_month >= 2.0;
explain analyze SELECT * FROM promotion;
explain analyze SELECT * FROM promotion;
explain analyze SELECT * FROM promotion;
explain analyze SELECT * FROM customer WHERE customer.birth_month <= 12.0 AND customer.birth_month >= 8.0;
explain analyze SELECT * FROM item WHERE item.manufact_id <= 484.0 AND item.manufact_id >= 311.0;
explain analyze SELECT * FROM store;
explain analyze SELECT * FROM store;
explain analyze SELECT * FROM promotion WHERE promotion.cost <= 1000.0 AND promotion.cost >= 1000.0;
explain analyze SELECT * FROM store WHERE store.devision_id <= 1 AND store.devision_id >= 1 AND store.company_id <= 255 AND store.company_id >= 27;
explain analyze SELECT * FROM store WHERE store.number_employees <= 297 AND store.number_employees >= 236 AND store.company_id <= 877 AND store.company_id >= 767;
explain analyze SELECT * FROM promotion;
explain analyze SELECT * FROM item WHERE item.class_id <= 6.0 AND item.class_id >= 3.0;
explain analyze SELECT * FROM store;
explain analyze SELECT * FROM store_sales WHERE store_sales.list_price <= 119.5 AND store_sales.list_price >= 30.57 AND store_sales.ext_coupon_amt <= 0.0 AND store_sales.ext_coupon_amt >= 0.0;
explain analyze SELECT * FROM customer;
explain analyze SELECT * FROM promotion WHERE promotion.cost <= 1000.0 AND promotion.cost >= 1000.0;
explain analyze SELECT * FROM customer;
explain analyze SELECT * FROM store_sales WHERE store_sales.list_price <= 148.98 AND store_sales.list_price >= -1.0 AND store_sales.sales_price <= 73.47 AND store_sales.sales_price >= 1.68 AND store_sales.ext_sales_price <= 4302.15 AND store_sales.ext_sales_price >= 181.67 AND store_sales.ext_coupon_amt <= 0.0 AND store_sales.ext_coupon_amt >= 0.0;
explain analyze SELECT * FROM customer;
explain analyze SELECT * FROM customer;
explain analyze SELECT * FROM store_sales WHERE store_sales.net_profit <= -237.9 AND store_sales.net_profit >= -1043.0;
explain analyze SELECT * FROM customer;
explain analyze SELECT * FROM customer WHERE customer.birth_year <= 1984.0 AND customer.birth_year >= 1961.0;
explain analyze SELECT * FROM store_sales WHERE store_sales.list_price <= 70.89 AND store_sales.list_price >= 33.68 AND store_sales.ext_sales_price <= 3957.75 AND store_sales.ext_sales_price >= 491.84 AND store_sales.ext_tax <= 83.49 AND store_sales.ext_tax >= 0.0 AND store_sales.ext_coupon_amt <= 0.0 AND store_sales.ext_coupon_amt >= 0.0;
explain analyze SELECT * FROM store_sales WHERE store_sales.quantity <= 72.0 AND store_sales.quantity >= 39.0 AND store_sales.list_price <= 153.31 AND store_sales.list_price >= 11.4 AND store_sales.ext_discount_amt <= 134.35 AND store_sales.ext_discount_amt >= 0.0 AND store_sales.ext_coupon_amt <= 1400.72 AND store_sales.ext_coupon_amt >= 0.0 AND store_sales.net_paid <= 5379.2 AND store_sales.net_paid >= 78.7 AND store_sales.net_profit <= 1014.0 AND store_sales.net_profit >= -2205.9;
explain analyze SELECT * FROM promotion;
explain analyze SELECT * FROM item WHERE item.current_price <= 1.09 AND item.current_price >= 0.72 AND item.brand_id <= 10006014.0 AND item.brand_id >= 1004001.0;
explain analyze SELECT * FROM promotion WHERE promotion.cost <= 1000.0 AND promotion.cost >= 1000.0;
explain analyze SELECT * FROM item;
explain analyze SELECT * FROM customer;
explain analyze SELECT * FROM promotion WHERE promotion.cost <= 1000.0 AND promotion.cost >= 1000.0;
explain analyze SELECT * FROM promotion WHERE promotion.cost <= 1000.0 AND promotion.cost >= 1000.0;
explain analyze SELECT * FROM store WHERE store.market_id <= 8 AND store.market_id >= 7 AND store.devision_id <= 1 AND store.devision_id >= 1 AND store.company_id <= 767 AND store.company_id >= 175;
explain analyze SELECT * FROM store_sales WHERE store_sales.ext_list_price <= 2186.53 AND store_sales.ext_list_price >= 1690.11 AND store_sales.net_paid <= 4892.45 AND store_sales.net_paid >= 352.8 AND store_sales.net_profit <= -219.1 AND store_sales.net_profit >= -1271.91;
explain analyze SELECT * FROM store WHERE store.market_id <= 8 AND store.market_id >= 4 AND store.devision_id <= 1 AND store.devision_id >= 1 AND store.tax_percentage <= 0.03 AND store.tax_percentage >= 0.03;
explain analyze SELECT * FROM promotion WHERE promotion.response_target <= 1.0 AND promotion.response_target >= 1.0;
explain analyze SELECT * FROM store_sales WHERE store_sales.net_paid <= 8496.8 AND store_sales.net_paid >= 3634.74 AND store_sales.net_profit <= 1857.87 AND store_sales.net_profit >= -1.0;
explain analyze SELECT * FROM store_sales WHERE store_sales.list_price <= 95.05 AND store_sales.list_price >= 24.92 AND store_sales.sales_price <= 49.27 AND store_sales.sales_price >= 13.38 AND store_sales.ext_wholesale_cost <= 1986.16 AND store_sales.ext_wholesale_cost >= 1543.48 AND store_sales.ext_list_price <= 3645.0 AND store_sales.ext_list_price >= 124.65 AND store_sales.ext_coupon_amt <= 0.0 AND store_sales.ext_coupon_amt >= 0.0;
explain analyze SELECT * FROM item;
explain analyze SELECT * FROM customer;
explain analyze SELECT * FROM store_sales WHERE store_sales.list_price <= 104.93 AND store_sales.list_price >= 33.66 AND store_sales.sales_price <= 51.3 AND store_sales.sales_price >= 42.74 AND store_sales.ext_list_price <= 5525.2 AND store_sales.ext_list_price >= -1.0 AND store_sales.ext_tax <= 5.75 AND store_sales.ext_tax >= 0.0;
explain analyze SELECT * FROM store_sales WHERE store_sales.list_price <= 81.62 AND store_sales.list_price >= 76.96 AND store_sales.ext_discount_amt <= 344.2 AND store_sales.ext_discount_amt >= 206.73 AND store_sales.ext_sales_price <= 655.34 AND store_sales.ext_sales_price >= 228.92 AND store_sales.ext_list_price <= 5296.83 AND store_sales.ext_list_price >= 638.08;
explain analyze SELECT * FROM promotion WHERE promotion.cost <= 1000.0 AND promotion.cost >= 1000.0;
explain analyze SELECT * FROM store_sales WHERE store_sales.list_price <= 80.23 AND store_sales.list_price >= 59.79 AND store_sales.ext_list_price <= 2469.84 AND store_sales.ext_list_price >= 979.52 AND store_sales.ext_coupon_amt <= 0.0 AND store_sales.ext_coupon_amt >= 0.0 AND store_sales.net_paid <= 287.76 AND store_sales.net_paid >= -1.0 AND store_sales.net_paid_inc_tax <= 6743.93 AND store_sales.net_paid_inc_tax >= 30.24 AND store_sales.net_profit <= -134.08 AND store_sales.net_profit >= -409.5;
explain analyze SELECT * FROM promotion;
explain analyze SELECT * FROM customer WHERE customer.birth_year <= 1948.0 AND customer.birth_year >= 1932.0;
explain analyze SELECT * FROM item WHERE item.class_id <= 8.0 AND item.class_id >= 1.0;
explain analyze SELECT * FROM promotion WHERE promotion.cost <= 1000.0 AND promotion.cost >= 1000.0;
explain analyze SELECT * FROM promotion WHERE promotion.cost <= 1000.0 AND promotion.cost >= 1000.0;
explain analyze SELECT * FROM customer WHERE customer.birth_day <= 13.0 AND customer.birth_day >= 6.0;
explain analyze SELECT * FROM promotion WHERE promotion.cost <= 1000.0 AND promotion.cost >= 1000.0;
explain analyze SELECT * FROM promotion;
explain analyze SELECT * FROM store_sales WHERE store_sales.ext_wholesale_cost <= 757.35 AND store_sales.ext_wholesale_cost >= 22.22 AND store_sales.ext_tax <= 101.6 AND store_sales.ext_tax >= 0.11 AND store_sales.ext_coupon_amt <= 0.0 AND store_sales.ext_coupon_amt >= 0.0 AND store_sales.net_profit <= 932.4 AND store_sales.net_profit >= 389.61;
explain analyze SELECT * FROM store_sales WHERE store_sales.quantity <= 15.0 AND store_sales.quantity >= 8.0 AND store_sales.list_price <= 92.55 AND store_sales.list_price >= 75.0 AND store_sales.ext_sales_price <= 2149.35 AND store_sales.ext_sales_price >= 1058.96 AND store_sales.ext_list_price <= 6050.22 AND store_sales.ext_list_price >= 999.6 AND store_sales.net_paid <= 434.1 AND store_sales.net_paid >= 76.0;
explain analyze SELECT * FROM store_sales WHERE store_sales.quantity <= 87.0 AND store_sales.quantity >= 19.0 AND store_sales.ext_list_price <= 8508.0 AND store_sales.ext_list_price >= 5653.23 AND store_sales.ext_tax <= 34.49 AND store_sales.ext_tax >= 14.81 AND store_sales.ext_coupon_amt <= 0.0 AND store_sales.ext_coupon_amt >= 0.0 AND store_sales.net_paid <= 1049.52 AND store_sales.net_paid >= 7.27;
explain analyze SELECT * FROM customer;
explain analyze SELECT * FROM store WHERE store.number_employees <= 297 AND store.number_employees >= 229 AND store.devision_id <= 1 AND store.devision_id >= 1 AND store.tax_percentage <= 0.03 AND store.tax_percentage >= 0.01;
explain analyze SELECT * FROM promotion;
explain analyze SELECT * FROM item WHERE item.class_id <= 5.0 AND item.class_id >= 1.0 AND item.manufact_id <= 256.0 AND item.manufact_id >= 256.0;
explain analyze SELECT * FROM promotion;
explain analyze SELECT * FROM store WHERE store.tax_percentage <= 0.03 AND store.tax_percentage >= 0.03;
explain analyze SELECT * FROM item WHERE item.current_price <= 4.0 AND item.current_price >= 1.93 AND item.manufact_id <= 335.0 AND item.manufact_id >= 53.0;
explain analyze SELECT * FROM customer;
explain analyze SELECT * FROM item;
explain analyze SELECT * FROM store_sales WHERE store_sales.ext_sales_price <= 4007.22 AND store_sales.ext_sales_price >= 1490.68 AND store_sales.ext_coupon_amt <= 0.0 AND store_sales.ext_coupon_amt >= 0.0;
explain analyze SELECT * FROM item WHERE item.current_price <= 5.13 AND item.current_price >= 3.94;
explain analyze SELECT * FROM item WHERE item.category_id <= 7.0 AND item.category_id >= 4.0 AND item.manufact_id <= 457.0 AND item.manufact_id >= 44.0;
explain analyze SELECT * FROM store_sales WHERE store_sales.quantity <= 85.0 AND store_sales.quantity >= 83.0 AND store_sales.list_price <= 58.02 AND store_sales.list_price >= 22.95 AND store_sales.sales_price <= 139.54 AND store_sales.sales_price >= 11.94 AND store_sales.ext_wholesale_cost <= 3902.8 AND store_sales.ext_wholesale_cost >= 1053.92 AND store_sales.ext_list_price <= 3412.2 AND store_sales.ext_list_price >= 613.76 AND store_sales.net_paid_inc_tax <= 1482.2 AND store_sales.net_paid_inc_tax >= 79.31;
explain analyze SELECT * FROM promotion;
explain analyze SELECT * FROM customer;
explain analyze SELECT * FROM customer;
explain analyze SELECT * FROM store_sales WHERE store_sales.net_profit <= 503.4 AND store_sales.net_profit >= -549.94;
explain analyze SELECT * FROM store_sales WHERE store_sales.sales_price <= 146.78 AND store_sales.sales_price >= 86.36 AND store_sales.ext_wholesale_cost <= 1785.0 AND store_sales.ext_wholesale_cost >= 796.2 AND store_sales.ext_list_price <= 5408.48 AND store_sales.ext_list_price >= 179.1 AND store_sales.ext_tax <= 146.89 AND store_sales.ext_tax >= 29.27 AND store_sales.net_paid <= 2593.25 AND store_sales.net_paid >= 670.65;
explain analyze SELECT * FROM customer WHERE customer.birth_year <= 1945.0 AND customer.birth_year >= 1941.0;
explain analyze SELECT * FROM customer;
explain analyze SELECT * FROM promotion;
explain analyze SELECT * FROM store_sales WHERE store_sales.quantity <= 82.0 AND store_sales.quantity >= 13.0 AND store_sales.ext_discount_amt <= 0.0 AND store_sales.ext_discount_amt >= 0.0 AND store_sales.ext_list_price <= 2203.6 AND store_sales.ext_list_price >= 37.26 AND store_sales.ext_tax <= 30.49 AND store_sales.ext_tax >= -1.0 AND store_sales.ext_coupon_amt <= 1590.07 AND store_sales.ext_coupon_amt >= 0.0;
explain analyze SELECT * FROM store_sales WHERE store_sales.ext_sales_price <= 2180.4 AND store_sales.ext_sales_price >= 963.84 AND store_sales.net_paid <= 2158.8 AND store_sales.net_paid >= 1251.36;
explain analyze SELECT * FROM store_sales WHERE store_sales.quantity <= 81.0 AND store_sales.quantity >= 57.0 AND store_sales.ext_coupon_amt <= 182.31 AND store_sales.ext_coupon_amt >= 0.0 AND store_sales.net_paid <= 6088.44 AND store_sales.net_paid >= 5921.55 AND store_sales.net_paid_inc_tax <= 7612.43 AND store_sales.net_paid_inc_tax >= 1473.55;
explain analyze SELECT * FROM store_sales;
explain analyze SELECT * FROM customer;
explain analyze SELECT * FROM item WHERE item.brand_id <= 9007006.0 AND item.brand_id >= 3004001.0 AND item.manufact_id <= 584.0 AND item.manufact_id >= 204.0;
explain analyze SELECT * FROM customer;
explain analyze SELECT * FROM customer WHERE customer.birth_year <= 1991.0 AND customer.birth_year >= 1935.0;
explain analyze SELECT * FROM item WHERE item.category_id <= 8.0 AND item.category_id >= 2.0;
explain analyze SELECT * FROM item;
explain analyze SELECT * FROM customer WHERE customer.birth_month <= 10.0 AND customer.birth_month >= 6.0;
explain analyze SELECT * FROM store_sales WHERE store_sales.list_price <= 147.64 AND store_sales.list_price >= 45.44 AND store_sales.sales_price <= 58.47 AND store_sales.sales_price >= 47.92 AND store_sales.net_paid <= 6361.87 AND store_sales.net_paid >= 0.0 AND store_sales.net_profit <= -160.16 AND store_sales.net_profit >= -943.93;
explain analyze SELECT * FROM store WHERE store.devision_id <= 1 AND store.devision_id >= 1 AND store.tax_percentage <= 0.08 AND store.tax_percentage >= 0.03;
explain analyze SELECT * FROM promotion WHERE promotion.response_target <= 1.0 AND promotion.response_target >= 1.0;
explain analyze SELECT * FROM store WHERE store.number_employees <= 288 AND store.number_employees >= 236 AND store.tax_percentage <= 0.08 AND store.tax_percentage >= 0.03;
explain analyze SELECT * FROM item WHERE item.current_price <= 5.98 AND item.current_price >= 1.45 AND item.category_id <= 10.0 AND item.category_id >= 8.0;
explain analyze SELECT * FROM item WHERE item.brand_id <= 10016009.0 AND item.brand_id >= 3002001.0 AND item.manufact_id <= 158.0 AND item.manufact_id >= 136.0;
explain analyze SELECT * FROM store_sales WHERE store_sales.quantity <= 76.0 AND store_sales.quantity >= 64.0 AND store_sales.ext_sales_price <= 1438.2 AND store_sales.ext_sales_price >= 348.12 AND store_sales.ext_wholesale_cost <= 1958.78 AND store_sales.ext_wholesale_cost >= 122.4;
explain analyze SELECT * FROM store_sales WHERE store_sales.list_price <= 24.6 AND store_sales.list_price >= -1.0 AND store_sales.ext_sales_price <= 1498.86 AND store_sales.ext_sales_price >= 749.45 AND store_sales.net_paid <= 867.6 AND store_sales.net_paid >= 708.4;
explain analyze SELECT * FROM store WHERE store.number_employees <= 245 AND store.number_employees >= 245 AND store.devision_id <= 1 AND store.devision_id >= 1;
explain analyze SELECT * FROM item WHERE item.manufact_id <= 365.0 AND item.manufact_id >= 150.0;
explain analyze SELECT * FROM customer;
explain analyze SELECT * FROM promotion WHERE promotion.response_target <= 1.0 AND promotion.response_target >= 1.0;
explain analyze SELECT * FROM store_sales;
explain analyze SELECT * FROM item;
explain analyze SELECT * FROM store_sales;
explain analyze SELECT * FROM customer;
explain analyze SELECT * FROM store;
explain analyze SELECT * FROM store_sales WHERE store_sales.list_price <= 119.64 AND store_sales.list_price >= 54.7 AND store_sales.sales_price <= 41.27 AND store_sales.sales_price >= 9.41 AND store_sales.ext_list_price <= 7043.4 AND store_sales.ext_list_price >= 2906.25;
explain analyze SELECT * FROM store_sales WHERE store_sales.ext_list_price <= 3043.84 AND store_sales.ext_list_price >= 365.28 AND store_sales.net_paid_inc_tax <= 245.28 AND store_sales.net_paid_inc_tax >= 165.39;
explain analyze SELECT * FROM store_sales WHERE store_sales.ext_discount_amt <= 0.0 AND store_sales.ext_discount_amt >= 0.0 AND store_sales.net_paid_inc_tax <= 1623.02 AND store_sales.net_paid_inc_tax >= 371.96;
explain analyze SELECT * FROM customer WHERE customer.birth_month <= 3.0 AND customer.birth_month >= 2.0;
explain analyze SELECT * FROM store WHERE store.devision_id <= 1 AND store.devision_id >= 1 AND store.company_id <= 877 AND store.company_id >= 27;
explain analyze SELECT * FROM item WHERE item.brand_id <= 10015013.0 AND item.brand_id >= 6009006.0 AND item.manufact_id <= 630.0 AND item.manufact_id >= 562.0;
explain analyze SELECT * FROM customer WHERE customer.birth_month <= 9.0 AND customer.birth_month >= 8.0;
explain analyze SELECT * FROM store_sales WHERE store_sales.ext_wholesale_cost <= 6899.04 AND store_sales.ext_wholesale_cost >= -1.0 AND store_sales.ext_tax <= 103.97 AND store_sales.ext_tax >= 20.72 AND store_sales.net_paid <= 2737.8 AND store_sales.net_paid >= 1651.86;
explain analyze SELECT * FROM promotion WHERE promotion.cost <= 1000.0 AND promotion.cost >= 1000.0;
explain analyze SELECT * FROM store_sales WHERE store_sales.list_price <= 137.75 AND store_sales.list_price >= 66.26 AND store_sales.ext_discount_amt <= 0.0 AND store_sales.ext_discount_amt >= 0.0 AND store_sales.ext_list_price <= 1862.08 AND store_sales.ext_list_price >= 1405.5;
explain analyze SELECT * FROM promotion WHERE promotion.response_target <= 1.0 AND promotion.response_target >= 1.0;
explain analyze SELECT * FROM customer WHERE customer.birth_month <= 5.0 AND customer.birth_month >= 2.0;
explain analyze SELECT * FROM item WHERE item.current_price <= 17.28 AND item.current_price >= 3.15 AND item.class_id <= 9.0 AND item.class_id >= 4.0;
explain analyze SELECT * FROM store_sales WHERE store_sales.list_price <= 32.41 AND store_sales.list_price >= 32.36 AND store_sales.ext_coupon_amt <= 336.86 AND store_sales.ext_coupon_amt >= 0.0 AND store_sales.net_paid_inc_tax <= 680.03 AND store_sales.net_paid_inc_tax >= 106.27;
explain analyze SELECT * FROM customer WHERE customer.birth_month <= 10.0 AND customer.birth_month >= 1.0;
explain analyze SELECT * FROM store WHERE store.floor_space <= 9026222 AND store.floor_space >= 5219562 AND store.company_id <= 811 AND store.company_id >= 255;
explain analyze SELECT * FROM customer WHERE customer.birth_year <= 1970.0 AND customer.birth_year >= 1924.0;
explain analyze SELECT * FROM customer;
explain analyze SELECT * FROM store;
explain analyze SELECT * FROM promotion WHERE promotion.response_target <= 1.0 AND promotion.response_target >= 1.0;
explain analyze SELECT * FROM item WHERE item.class_id <= 15.0 AND item.class_id >= 3.0;
explain analyze SELECT * FROM store WHERE store.market_id <= 8 AND store.market_id >= 7 AND store.devision_id <= 1 AND store.devision_id >= 1;
explain analyze SELECT * FROM customer WHERE customer.birth_year <= 1978.0 AND customer.birth_year >= 1939.0;
explain analyze SELECT * FROM store WHERE store.floor_space <= 9294113 AND store.floor_space >= 8954883 AND store.devision_id <= 1 AND store.devision_id >= 1;
explain analyze SELECT * FROM customer;
explain analyze SELECT * FROM store_sales WHERE store_sales.ext_coupon_amt <= 0.0 AND store_sales.ext_coupon_amt >= 0.0;
explain analyze SELECT * FROM promotion WHERE promotion.response_target <= 1.0 AND promotion.response_target >= 1.0;
explain analyze SELECT * FROM customer;
explain analyze SELECT * FROM promotion WHERE promotion.cost <= 1000.0 AND promotion.cost >= 1000.0;
explain analyze SELECT * FROM item WHERE item.brand_id <= 10002008.0 AND item.brand_id >= 3004002.0;
explain analyze SELECT * FROM item WHERE item.class_id <= 16.0 AND item.class_id >= 4.0 AND item.category_id <= 9.0 AND item.category_id >= 4.0;
explain analyze SELECT * FROM customer WHERE customer.birth_year <= 1992.0 AND customer.birth_year >= 1945.0;
explain analyze SELECT * FROM store WHERE store.number_employees <= 297 AND store.number_employees >= 236 AND store.floor_space <= 8954883 AND store.floor_space >= 5250760 AND store.tax_percentage <= 0.06 AND store.tax_percentage >= 0.03;
explain analyze SELECT * FROM item;
explain analyze SELECT * FROM customer;
explain analyze SELECT * FROM promotion;
explain analyze SELECT * FROM item;
explain analyze SELECT * FROM promotion WHERE promotion.cost <= 1000.0 AND promotion.cost >= 1000.0;
explain analyze SELECT * FROM customer;
explain analyze SELECT * FROM customer WHERE customer.birth_month <= 5.0 AND customer.birth_month >= 1.0;
explain analyze SELECT * FROM item WHERE item.brand_id <= 9005007.0 AND item.brand_id >= 1003001.0 AND item.class_id <= 3.0 AND item.class_id >= 3.0;
explain analyze SELECT * FROM promotion WHERE promotion.response_target <= 1.0 AND promotion.response_target >= 1.0;
explain analyze SELECT * FROM store WHERE store.tax_percentage <= 0.08 AND store.tax_percentage >= 0.03;
explain analyze SELECT * FROM store_sales WHERE store_sales.quantity <= 100.0 AND store_sales.quantity >= 58.0 AND store_sales.list_price <= 122.9 AND store_sales.list_price >= 84.17 AND store_sales.ext_coupon_amt <= 0.0 AND store_sales.ext_coupon_amt >= 0.0 AND store_sales.net_profit <= -933.8 AND store_sales.net_profit >= -1371.89;
explain analyze SELECT * FROM item WHERE item.current_price <= 4.78 AND item.current_price >= 3.55;
explain analyze SELECT * FROM store WHERE store.number_employees <= 229 AND store.number_employees >= 218 AND store.tax_percentage <= 0.11 AND store.tax_percentage >= 0.03;
explain analyze SELECT * FROM store_sales WHERE store_sales.ext_wholesale_cost <= 4831.47 AND store_sales.ext_wholesale_cost >= 364.08 AND store_sales.ext_list_price <= 3885.69 AND store_sales.ext_list_price >= 3177.81 AND store_sales.ext_tax <= 159.26 AND store_sales.ext_tax >= 7.88;
explain analyze SELECT * FROM promotion WHERE promotion.response_target <= 1.0 AND promotion.response_target >= 1.0;
explain analyze SELECT * FROM customer WHERE customer.birth_day <= 13.0 AND customer.birth_day >= 9.0;
explain analyze SELECT * FROM store_sales WHERE store_sales.quantity <= 72.0 AND store_sales.quantity >= 21.0 AND store_sales.list_price <= 99.82 AND store_sales.list_price >= 92.29 AND store_sales.sales_price <= 8.99 AND store_sales.sales_price >= 4.61 AND store_sales.ext_discount_amt <= 0.0 AND store_sales.ext_discount_amt >= 0.0;
explain analyze SELECT * FROM store;
explain analyze SELECT * FROM store_sales WHERE store_sales.quantity <= 37.0 AND store_sales.quantity >= 19.0 AND store_sales.ext_discount_amt <= 0.0 AND store_sales.ext_discount_amt >= -1.0 AND store_sales.ext_wholesale_cost <= 2053.23 AND store_sales.ext_wholesale_cost >= 1737.32 AND store_sales.ext_tax <= 80.09 AND store_sales.ext_tax >= 34.27 AND store_sales.net_paid <= 6259.88 AND store_sales.net_paid >= 3082.32 AND store_sales.net_paid_inc_tax <= 8118.83 AND store_sales.net_paid_inc_tax >= 445.59;
explain analyze SELECT * FROM store WHERE store.company_id <= 811 AND store.company_id >= 27 AND store.tax_percentage <= 0.08 AND store.tax_percentage >= 0.06;
explain analyze SELECT * FROM store_sales WHERE store_sales.quantity <= 84.0 AND store_sales.quantity >= 33.0 AND store_sales.sales_price <= 4.5 AND store_sales.sales_price >= 0.0 AND store_sales.ext_discount_amt <= 0.0 AND store_sales.ext_discount_amt >= 0.0 AND store_sales.ext_sales_price <= 260.4 AND store_sales.ext_sales_price >= 138.33 AND store_sales.ext_wholesale_cost <= 4888.19 AND store_sales.ext_wholesale_cost >= 94.56 AND store_sales.ext_tax <= 0.48 AND store_sales.ext_tax >= 0.0;
explain analyze SELECT * FROM store_sales WHERE store_sales.list_price <= 49.64 AND store_sales.list_price >= 11.17 AND store_sales.sales_price <= 64.22 AND store_sales.sales_price >= 9.85 AND store_sales.ext_discount_amt <= 1993.3 AND store_sales.ext_discount_amt >= 0.0 AND store_sales.ext_sales_price <= 7278.52 AND store_sales.ext_sales_price >= 1246.95 AND store_sales.ext_wholesale_cost <= 486.57 AND store_sales.ext_wholesale_cost >= -1.0 AND store_sales.ext_list_price <= 5229.08 AND store_sales.ext_list_price >= 1513.8;
explain analyze SELECT * FROM store_sales WHERE store_sales.list_price <= 71.42 AND store_sales.list_price >= 61.2 AND store_sales.ext_sales_price <= 717.4 AND store_sales.ext_sales_price >= 119.42 AND store_sales.ext_tax <= 20.41 AND store_sales.ext_tax >= 4.77;
explain analyze SELECT * FROM item;
explain analyze SELECT * FROM store;
explain analyze SELECT * FROM store;
explain analyze SELECT * FROM store WHERE store.devision_id <= 1 AND store.devision_id >= 1;
explain analyze SELECT * FROM customer;
explain analyze SELECT * FROM store;
explain analyze SELECT * FROM customer WHERE customer.birth_year <= 1986.0 AND customer.birth_year >= 1944.0;
explain analyze SELECT * FROM item;
explain analyze SELECT * FROM customer;
explain analyze SELECT * FROM customer WHERE customer.birth_year <= 1976.0 AND customer.birth_year >= 1934.0;
explain analyze SELECT * FROM promotion WHERE promotion.response_target <= 1.0 AND promotion.response_target >= 1.0;
explain analyze SELECT * FROM item;
explain analyze SELECT * FROM promotion WHERE promotion.response_target <= 1.0 AND promotion.response_target >= 1.0;
explain analyze SELECT * FROM store_sales WHERE store_sales.list_price <= 95.13 AND store_sales.list_price >= 22.16 AND store_sales.ext_discount_amt <= 0.0 AND store_sales.ext_discount_amt >= 0.0 AND store_sales.ext_sales_price <= 473.77 AND store_sales.ext_sales_price >= 240.0 AND store_sales.ext_coupon_amt <= 31.01 AND store_sales.ext_coupon_amt >= -1.0;
explain analyze SELECT * FROM item WHERE item.current_price <= 6.07 AND item.current_price >= 1.92 AND item.category_id <= 10.0 AND item.category_id >= 5.0;
explain analyze SELECT * FROM promotion;
explain analyze SELECT * FROM promotion;
explain analyze SELECT * FROM promotion;
explain analyze SELECT * FROM store WHERE store.number_employees <= 294 AND store.number_employees >= 278 AND store.market_id <= 10 AND store.market_id >= 8 AND store.company_id <= 220 AND store.company_id >= 27;
explain analyze SELECT * FROM promotion WHERE promotion.response_target <= 1.0 AND promotion.response_target >= 1.0;
explain analyze SELECT * FROM customer;
explain analyze SELECT * FROM promotion WHERE promotion.response_target <= 1.0 AND promotion.response_target >= 1.0;
explain analyze SELECT * FROM item WHERE item.brand_id <= 9007012.0 AND item.brand_id >= 3003001.0;
explain analyze SELECT * FROM store_sales WHERE store_sales.net_profit <= -203.07 AND store_sales.net_profit >= -685.62;
explain analyze SELECT * FROM customer WHERE customer.birth_month <= 5.0 AND customer.birth_month >= 4.0;
explain analyze SELECT * FROM store_sales WHERE store_sales.sales_price <= 72.77 AND store_sales.sales_price >= 7.8 AND store_sales.ext_list_price <= 13422.1 AND store_sales.ext_list_price >= 1000.22 AND store_sales.ext_tax <= 7.18 AND store_sales.ext_tax >= 0.0 AND store_sales.ext_coupon_amt <= 0.0 AND store_sales.ext_coupon_amt >= 0.0;
explain analyze SELECT * FROM store;
explain analyze SELECT * FROM promotion;
explain analyze SELECT * FROM item;
explain analyze SELECT * FROM item;
explain analyze SELECT * FROM item WHERE item.brand_id <= 5002002.0 AND item.brand_id >= 1003002.0 AND item.category_id <= 3.0 AND item.category_id >= 2.0;
explain analyze SELECT * FROM store WHERE store.floor_space <= 9341467 AND store.floor_space >= 7557959 AND store.market_id <= 7 AND store.market_id >= 2 AND store.devision_id <= 1 AND store.devision_id >= 1;
explain analyze SELECT * FROM store_sales WHERE store_sales.list_price <= 173.65 AND store_sales.list_price >= 92.35;
explain analyze SELECT * FROM store WHERE store.tax_percentage <= 0.08 AND store.tax_percentage >= 0.03;
explain analyze SELECT * FROM item WHERE item.category_id <= 6.0 AND item.category_id >= 4.0 AND item.manufact_id <= 747.0 AND item.manufact_id >= 59.0;
explain analyze SELECT * FROM customer WHERE customer.birth_day <= 30.0 AND customer.birth_day >= 19.0;
explain analyze SELECT * FROM customer WHERE customer.birth_day <= 20.0 AND customer.birth_day >= 4.0;
explain analyze SELECT * FROM item WHERE item.class_id <= 2.0 AND item.class_id >= 2.0 AND item.category_id <= 5.0 AND item.category_id >= 4.0;
explain analyze SELECT * FROM item WHERE item.category_id <= 10.0 AND item.category_id >= 9.0;
explain analyze SELECT * FROM customer WHERE customer.birth_day <= 12.0 AND customer.birth_day >= 10.0;
explain analyze SELECT * FROM customer WHERE customer.birth_year <= 1937.0 AND customer.birth_year >= 1928.0;
explain analyze SELECT * FROM item;
explain analyze SELECT * FROM item WHERE item.current_price <= 1.77 AND item.current_price >= -1.0 AND item.brand_id <= 6004007.0 AND item.brand_id >= 4003002.0;
explain analyze SELECT * FROM customer;
explain analyze SELECT * FROM item WHERE item.brand_id <= 7004006.0 AND item.brand_id >= 1001002.0;
explain analyze SELECT * FROM store WHERE store.number_employees <= 288 AND store.number_employees >= 236;
